[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "border adapt cage laptop mail chuckle cinnamon play beach angry interest drop wool inject rug donor immune fossil print doctor spread tuna move grape"
